# Generated by Django 5.0.2 on 2024-03-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_country_id_alter_state_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='state',
            old_name='countryId',
            new_name='country',
        ),
    ]
